services:
    Zikula\ContentModule\ContentType\AuthorType:
        parent: zikula.content_type.base
        shared: false
        arguments:
            - '@zikula_users_module.current_user'
            - '@zikula_users_module.user_repository'
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\AuthorType:
        parent: zikula.content_type.form.base
        arguments:
            - '@zikula_users_module.user_repository'
        tags: ['form.type']

    Zikula\ContentModule\ContentType\BlockType:
        parent: zikula.content_type.base
        shared: false
        arguments:
            - '@kernel'
            - '@router'
            - '@zikula_blocks_module.block_repository'
            - '@zikula_blocks_module.api.block'
            - '@zikula_core.common.theme_engine'
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\BlockType:
        parent: zikula.content_type.form.base
        arguments:
            - '@zikula_blocks_module.block_repository'
        tags: ['form.type']

    Zikula\ContentModule\ContentType\BreadcrumbType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setIgnoreFirstTreeLevel, ["@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'ignoreFirstTreeLevelInRoutes', true)"]]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\BreadcrumbType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\ComputerCodeType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setKernel, ['@kernel']]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\ComputerCodeType:
        parent: zikula.content_type.form.base
        arguments:
            - '@kernel'
        tags: ['form.type']

    Zikula\ContentModule\ContentType\ContentItemType:
        parent: zikula.content_type.base
        shared: false
        arguments:
            - '@zikula_content_module.entity_factory'
            - '@zikula_content_module.content_display_helper'
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\ContentItemType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\ControllerType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setKernel, ['@kernel']]
            - [setRequestStack, ['@request_stack']]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\ControllerType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\FeedType:
        parent: zikula.content_type.base
        shared: false
        arguments:
            - '@zikula_content_module.cache_helper'
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\FeedType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\GoogleMapType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setRequestStack, ['@request_stack']]
            - [setGoogleMapsApiKey, ["@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'googleMapsApiKey', '')"]]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\GoogleMapType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\GoogleRouteType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setRequestStack, ['@request_stack']]
            - [setGoogleMapsApiKey, ["@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'googleMapsApiKey', '')"]]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\GoogleRouteType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\HeadingType:
        parent: zikula.content_type.base
        shared: false
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\HeadingType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\HtmlType:
        parent: zikula.content_type.base
        shared: false
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\HtmlType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\LeafletMapType:
        parent: zikula.content_type.base
        shared: false
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\LeafletMapType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\PageNavigationType:
        parent: zikula.content_type.base
        shared: false
        tags: ['zikula.content_type']

    Zikula\ContentModule\ContentType\QuoteType:
        parent: zikula.content_type.base
        shared: false
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\QuoteType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\SlideshareType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setCacheHelper, ['@zikula_content_module.cache_helper']]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\SlideshareType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\TableOfContentsType:
        parent: zikula.content_type.base
        shared: false
        arguments:
            - '@router'
            - '@zikula_content_module.entity_factory'
            - '@zikula_content_module.content_display_helper'
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'ignoreFirstTreeLevelInRoutes', true)"
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\TableOfContentsType:
        parent: zikula.content_type.form.base
        arguments:
            - '@zikula_content_module.entity_factory'
        tags: ['form.type']

    Zikula\ContentModule\ContentType\TabNavigationType:
        parent: zikula.content_type.base
        shared: false
        arguments:
            - '@request_stack'
            - '@zikula_content_module.entity_factory'
            - '@zikula_content_module.content_display_helper'
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\TabNavigationType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\UnfilteredType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setEnableRawPlugin, ["@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'enableRawPlugin', false)"]]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\UnfilteredType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\VimeoType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setCacheHelper, ['@zikula_content_module.cache_helper']]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\VimeoType:
        parent: zikula.content_type.form.base
        tags: ['form.type']

    Zikula\ContentModule\ContentType\YouTubeType:
        parent: zikula.content_type.base
        shared: false
        calls:
            - [setCacheHelper, ['@zikula_content_module.cache_helper']]
        tags: ['zikula.content_type']
    Zikula\ContentModule\ContentType\Form\Type\YouTubeType:
        parent: zikula.content_type.form.base
        tags: ['form.type']
