services:
    zikula_content_module.cache_helper:
        class: Zikula\ContentModule\Helper\CacheHelper
        arguments:
            - '@filesystem'
            - '%kernel.cache_dir%/ZikulaContentModule/'
    zikula_content_module.content_display_helper:
        class: Zikula\ContentModule\Helper\ContentDisplayHelper
        arguments:
            - '@service_container'
            - '@translator.default'
            - '@zikula_theme_module.api.page_asset'
            - '@zikula_groups_module.group_repository'
    zikula_content_module.collector.content_type_collector:
        class: Zikula\ContentModule\Collector\ContentTypeCollector
    zikula_content_module.custom_twig_extension:
        class: Zikula\ContentModule\Twig\CustomTwigExtension
        arguments:
            - '@database_connection'
            - '@request_stack'
            - '@router'
            - '@zikula_content_module.collector.content_type_collector'
            - '@zikula_content_module.permission_helper'
            - '@zikula_content_module.content_display_helper'
            - '@zikula_content_module.category_helper'
            - '@zikula_categories_module.category_repository'
            - '@zikula_content_module.entity_factory'
            - '@zikula_content_module.collection_filter_helper'
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'countPageViews', false)"
        tags: ['twig.extension']
    zikula_content_module.form.type.content_item:
        class: Zikula\ContentModule\Form\Type\ContentItemType
        arguments:
            - '@translator.default'
            - '@zikula_content_module.listentries_helper'
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaContentModule', 'stylingClasses', '')"
        tags: ['form.type']
    zikula_content_module.form.type.move_copy_content_item:
        class: Zikula\ContentModule\Form\Type\MoveCopyContentItemType
        arguments:
            - '@translator.default'
            - '@zikula_content_module.entity_factory'
        tags: ['form.type']
    zikula_content_module.form.type.block.menu:
        class: Zikula\ContentModule\Block\Form\Type\MenuBlockType
        arguments:
            - '@translator.default'
            - '@zikula_content_module.entity_factory'
        tags: ['form.type']
    zikula_content_module.form.type.block.subpages:
        class: Zikula\ContentModule\Block\Form\Type\SubPagesBlockType
        arguments:
            - '@translator.default'
        tags: ['form.type']
    zikula_content_module.hook_subscriber.form_aware_hook.contentitems:
        class: Zikula\ContentModule\HookSubscriber\ContentItemFormAwareHookSubscriber
        arguments:
            - '@translator.default'
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulacontentmodule.form_aware_hook.contentitems' }
    zikula_content_module.hook_subscriber.ui_hooks.contentitems:
        class: Zikula\ContentModule\HookSubscriber\ContentItemUiHooksSubscriber
        arguments:
            - '@translator.default'
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.zikulacontentmodule.ui_hooks.contentitems' }
