services:
    zikula_content_module.link_container:
        class: Zikula\ContentModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_content_module.controller_helper"
            - "@zikula_content_module.permission_helper"
        tags: ['zikula.link_container']
